Repository GeorgeCimpoeru/backend_repo, pull requests merged in 2025-02, with the labels that each got.

#36 fix: add missing includes, delete obsolete tests, link missing object…
  ecu_simulation/BatteryModule/test/BatteryModuleTest.cpp
  ecu_simulation/DoorsModule/test/DoorsModuleTest.cpp
  ecu_simulation/EngineModule/test/EngineModuleTest.cpp
  ecu_simulation/HVACModule/test/HVACModuleTest.cpp
  mcu/Makefile
  mcu/test/MCUModuleTest.cpp
  mcu/test/ReceiveFramesTest.cpp
  ota/request_download/utest/RequestDownloadTest.cpp
  ota/request_download/utest/request_download.cpp
  ota/request_update_status/utest/RequestUpdateStatusTest.cpp
  uds/authentication/utest/SecurityAccessTest.cpp
  uds/clear_dtc/utest/ClearDtcTest.cpp
  uds/ecu_reset/utest/EcuResetTest.cpp
  uds/read_data_by_identifier/utest/ReadDataByIdentifierTest.cpp
  uds/read_dtc_information/utest/ReadDtcInformationTest.cpp
  uds/routine_control/utest/RoutineControlTest.cpp
  uds/tester_present/utest/TesterPresentTest.cpp
  uds/write_data_by_identifier/utest/WriteDataByIdentifierTest.cpp
  utils/test/GenerateFramesTest.cpp
  utils/test/HandleFramesTest.cpp
  utils/test/MemoryManagerTest.cpp
  utils/test/NegativeResponseTest.cpp
  utils/test/ReceiveFramesTest.cpp
Labels: bug

#42 fix: make ECU tests in allTests and clean ECU test files in both MCU and ECUs makefiles
  ecu_simulation/BatteryModule/Makefile
  ecu_simulation/DoorsModule/Makefile
  ecu_simulation/EngineModule/Makefile
  ecu_simulation/HVACModule/Makefile
  mcu/Makefile
Labels: bug

#41 fix: add Globals test object file
  mcu/Makefile
Labels: bug

#45 Separate testing code from production code
  ecu_simulation/BatteryModule/src/main.cpp
  ecu_simulation/DoorsModule/src/main.cpp
  ecu_simulation/EngineModule/src/main.cpp
  ecu_simulation/HVACModule/src/main.cpp
  mcu/Makefile
  mcu/src/main.cpp
  uds/ecu_reset/include/DummyEcuReset.h
  uds/ecu_reset/include/EcuReset.h
  uds/ecu_reset/src/DummyEcuReset.cpp
  uds/ecu_reset/src/EcuReset.cpp
  uds/ecu_reset/utest/EcuResetTest.cpp
Labels: enhancement

#48 Provide ReadMemoryByAddressUTs, mocks for memorymanager and generateframes, and include gmock in makefile
  mcu/Makefile
  mcu/src/MCUModule.cpp
  uds/read_memory_by_address/include/ReadMemoryByAddress.h
  uds/read_memory_by_address/src/ReadMemoryByAddress.cpp
  uds/read_memory_by_address/utest/ReadMemoryByAddressTest.cpp
  uds/routine_control/src/RoutineControl.cpp
  utils/include/GenerateFrames.h
  utils/include/IMemoryManager.h
  utils/include/MemoryManager.h
  utils/include/MockGenerateFrames.h
  utils/include/MockMemoryManager.h
  utils/include/TestUtils.h
  utils/src/ECU.cpp
  utils/src/TestUtils.cpp
Labels: test, refactor

#63 Feature/fix request update status uts
  ota/request_update_status/src/RequestUpdateStatus.cpp
  ota/request_update_status/utest/RequestUpdateStatusTest.cpp
Labels: bug, test

#61 test: provide TransferData UTs
  ota/transfer_data/src/TransferData.cpp
  ota/transfer_data/utest/TransferDataTest.cpp
Labels: bug, test

#64 feat: add makefile targets to run/clean all Unit tests directly from …
  mcu/Makefile
Labels: Up to date

#62 Feature/request download uts
  ota/request_download/utest/RequestDownloadTest.cpp
  utils/include/TestUtils.h
  utils/src/TestUtils.cpp
Labels: test
